# 4. Déploiement de l'application interactive

## 4.1. Préliminaires (🔵,🔴,⚫)

L'application construite dans la partie précédente reste pour le moment à un niveau local: elle n'est accessible que via l'utilisateur qui l'a déployée et ce sur la machine où elle a été déployée. L'objectif de cette dernière partie est de **déployer** l'application, c'est à dire de la rendre accessible en continu à n'importe quel utilisateur. Pour cela, on va devoir s'intéresser à la technologie des **conteneurs**, qui est à la base des infrastructures de production modernes.

Le fait de lancer ce notebook via un simple [lien de lancement](LIEN A METTRE) nous a permis de commencer à travailler directement, sans trop nous soucier de l'environnement de développement dans lequel on se trouvait. Mais dès lors que l'on souhaite passer de son environnement de développement à un environnement de production, il est nécessaire de se poser un ensemble de questions pour s'assurer que le projet fonctionne ailleurs que sur sa machine personnelle :
- quelle est la version de `Python` à installer pour que le projet fonctionne ?
- quels sont les packages `Python` utilisés par le projet et quelles sont leurs versions ?
- quelles sont les éventuelles librairies systèmes, i.e. dépendantes du système d'exploitation installé, nécessaires pour que les packages `Python` s'installent correctement ?

La technologie standard pour assurer la **portabilité** d'un projet, c'est à dire de fonctionner sur différents environnements informatiques, est celle des **conteneurs**. Schématiquement, il s'agit de boîtes virtuelles qui contiennent l'ensemble de l’environnement (librairies systèmes, interpréteur `Python`, code applicatif, configuration...) permettant de faire tourner l’application, tout en restant légères et donc faciles à redistribuer. En fait, chaque service lancé sur le `SSP Cloud` est un conteneur, et ce notebook tourne donc lui-même... dans un conteneur ! L'enjeu de cette partie est donc de dévoiler pas à pas la boîte noire afin de comprendre dans quel environnement on se trouve, et comment celui-ci va nous permettre de déployer notre application.

## Conteneurisation de l'application (🔵,🔴,⚫)

::: {.cell .markdown}
<!----- boite 🔵 ----->

```{=html}
```{python}
#| echo: false
#| output: asis
#| eval: true
from utils_notebook import create_box_level
create_box_level(color = "🔵", title = "Comprendre la création de l'image `Docker` de l'application (🔵)")
```
<details>
<summary>Dérouler pour révéler les instructions</summary>
```

Le projet contient à la racine un fichier `Dockerfile`. Il s'agit de la "recette" de construction de l'image `Docker` de l'application, i.e. qui spécifie l'environnement nécessaire à son bon fonctionnement. En vous inspirant de la [documentation Streamlit](https://docs.streamlit.io/knowledge-base/tutorials/deploy/docker#create-a-dockerfile) (en Anglais) ou bien de cette [page de cours](https://ensae-reproductibilite.github.io/website/chapters/portability.html#dockerfile), essayez de comprendre pas à pas les étapes de construction de l'image `Docker` de l'application.

```{=html}
</details>
</div>
```

<!----- end 🔵 ----->
:::

::: {.cell .markdown}
<!----- boite 🔴, ⚫ ----->

```{=html}
```{python}
#| echo: false
#| output: asis
#| eval: true
from utils_notebook import create_box_level
create_box_level(color = "grey", title = "Créer le `Dockerfile` de l'application (🔴, ⚫)")
```
<details>
<summary>Dérouler pour révéler les instructions</summary>
```

Une image `Docker` est construite à partir d'un fichier spécifique généralement placé à la racine du projet, le `Dockerfile`. Sans regarder le `Dockerfile` existant dans le projet, et en vous inspirant de la [documentation Streamlit](https://docs.streamlit.io/knowledge-base/tutorials/deploy/docker#create-a-dockerfile) (en Anglais) essayez de construire le `Dockerfile` pertinent pour l'application, puis comparez votre solution à l'existant. Quelques consignes supplémentaires :
- on utilisera comme image de base `inseefrlab/onyxia-jupyter-python:py3.10.9`
- on se mettra en utilisateur *root* via l'[instruction USER](https://docs.docker.com/engine/reference/builder/#user)
- on aura besoin d'installer les librairies système suivantes via `apt-get` : `ffmpeg, libsm6, libxext6, libzbar0`
- on copiera tous les fichiers du projet local sur l'image `Docker` à l'aide de l'[instruction COPY](https://docs.docker.com/engine/reference/builder/#copy)
- on fera tourner l'application sur le port `8000` du conteneur (qu'il faudra donc prendre soin d'exposer)
- on ne fera pas de `HEALTHCHECK`

```{=html}
</details>
</div>
```

<!----- end 🔴, ⚫ ----->
:::

::: {.cell .markdown}
<!----- boite ⚫ ----->

```{=html}
```{python}
#| echo: false
#| output: asis
#| eval: true
from utils_notebook import create_box_level
create_box_level(color = "⚫", title = "Construire l'image `Docker` de l'application par intégration continue (⚫)")
```
<details>
<summary>Dérouler pour révéler les instructions</summary>
```

Une fois le `Dockerfile` construit (du moins sa première version), on va l'utiliser pour construire une image `Docker` (la "boîte" virtuelle) et mettre celle-ci sur un registre (répertoire d'images) afin que celle-ci puisse être réutilisée dans un autre environnement que celui où on l'a développée. On pourrait faire cela "à la main" en ligne de commandes (cf. [documentation Docker](https://docs.docker.com/get-started/02_our_app/)), mais on va plutôt automatiser le processus en passant par un *pipeline* (série d'étapes) d'intégration continue. Ainsi, à chaque mise à jour du code source de l'application (nouvelles fonctionnalités, correction de bugs, etc.), notre image sera automatiquement mise à jour.

Les étapes à suivre sont les suivantes :
- si nécessaire, créer un compte personnel sur [GitHub](https://github.com) et sur le [DockerHub](https://hub.docker.com/) (registre d'images open-source)
- bien s'assurer que le `Dockerfile` obtenu à l'étape précédente est identique à celui existant dans le projet
- [forker](https://docs.github.com/fr/get-started/quickstart/fork-a-repo) le [dépôt du projet](https://github.com/InseeFrLab/funathon2023_sujet4) afin de l'avoir dans votre espace personnel sur `GitHub`
- [cloner](https://docs.github.com/fr/repositories/creating-and-managing-repositories/cloning-a-repository) le dépôt forké (i.e. de la forme `votre_nom_utilisateur_gh/funathon2023_sujet4`) via un terminal
- créer un nouveau dépôt public sur le `DockerHub`
- créer les secrets `DOCKERHUB_USERNAME` et `DOCKERHUB_TOKEN` (cf. [documentation Docker](https://docs.docker.com/build/ci/github-actions/#step-one-create-the-repository)), nécessaires pour que le CI `GitHub` puisse pousser une image sur le `DockerHub`
- ajuster le fichier d'intégration continue (`.github/workflows/docker.yaml`) pour que le dépôt sur lequel est envoyé l'image ne soit plus `inseefrlab/funathon2023_sujet4` mais `votre_nom_utilisateur_dh/funathon2023_sujet4`
- *commit*/*push* les changements sur `GitHub`
- si tout s'est bien passé, une action devrait se lancer (cf. onglet `Actions` du dépôt) afin de construire l'image et de l'envoyer sur le `DockerHub`
- si l'action s'est bien déroulée (flèche verte), aller vérifier que l'image est bien disponible dans votre espace sur le `DockerHub`

```{=html}
</details>
</div>
```

<!----- end ⚫ ----->
:::



## Déploiement sur le `SSP Cloud`

Maintenant que l'image de notre application est disponible sur le `DockerHub`, elle peut à présent être récupérée (*pull*) et déployée sur n'importe quel environnement. Dans notre cas, on va la déployer sur un cluster `Kubernetes`, l'infrastructure sous-jacente du `SSP Cloud`. Le fonctionnement de `Kubernetes` est assez technique, mais l'on pourra s'abstraire de certaines parties selon le niveau de difficulté choisi.


::: {.cell .markdown}
<!----- boite 🔴,⚫ ----->

```{=html}
```{python}
#| echo: false
#| output: asis
#| eval: true
from utils_notebook import create_box_level
create_box_level(color = "grey", title = "Déploiement de l'application à partir du `DockerHub` `InseeFrLab` (🔴,⚫)")
```
<details>
<summary>Dérouler pour révéler les instructions</summary>
```

En amont de ce projet, nous avons construit une image `Docker` fonctionnelle de l'application, disponible sur le `DockerHub` dans l'espace [inseefrlab](https://hub.docker.com/repository/docker/inseefrlab/funathon2023_sujet4). Nous avons également créés dans le répertoire `deployment/` à la racine du projet les trois fichiers standards nécessaires au déploiement d'une application sur `Kubernetes`. 

Afin de déployer l'application, suivre les instructions suivantes :
- inspecter les fichiers `deployment.yml`, `service.yml` et `ingress.yml` et repérer les éléments suivants :
    - où est spécifiée l'image que l'on va déployer. Pour la difficulté ⚫: remplacer l'image actuelle par celle que vous avez construite et envoyée sur le `DockerHub` dans la partie précédente
    - où sont spécifiées les ressources computationnelles que l'on va allouer à l'application
    - où est défini le port que l'on a exposé dans le `Dockerfile`
    - où est défini le port sur lequel on va exposer l'application sur le cluster `Kubernetes`
    - où est définie l'URL à laquelle on va exposer l'application pour que les utilisateurs puissent s'y connecter. La modifier (à 2 reprises) pour y indiquer une adresse personalisée pour votre déploiement. Seule contrainte : elle doit être de la forme : `*.lab.sspcloud.fr` 
- ouvrir un terminal dans le service `Jupyter`
- se placer dans le projet du funathon : `cd funathon2023_sujet4`
- appliquer les contrats de déploiement : `kubernetes apply -f deployment/`
- vérifier le lancement du conteneur : `watch kubernetes get pods`. Le nom associé devrait être de la forme `funathon2023-sujet4-****-*****`
- une fois que le conteneur est indiqué comme `Running`, entrer dans un navigateur l'URL que vous avez spécifié dans le fichier `ingress.yml`, et vérifier que l'application fonctionne correctement

```{=html}
</details>
</div>
```

<!----- end 🔴,⚫ ----->
:::

Votre application est maintenant déployée, vous pouvez partager cette URL avec n'importe quel utilisateur dans le monde !
